---
- hosts: vmlab
  user: student
  become: yes
  vars:
    apache_version: 2.6
    motd_warning: "WARNING: used by ICT faculty/students only.\n"
    testserver: yes
  tasks:
    - name: update apache
      action: yum name=httpd state=latest

    - name: remove tree
      action: yum name=tree state=absent

    - name: set hostname to SenecaID
      ansible.builtin.hostname:
        name: hzhao99

    - name: create user Seneca_ID with sudo access
      ansible.builtin.user:
        name: hzhao99
        create_home: yes
        password: '$6$93TEtDY1Z3fSXKRr$BDQWp81ubwSF8fJTtl65AoJNI3KslewWKnnVK/unuDCczoRHNgG5O7NjJfQHe2DgrVuLzbH.D.tGm.q6yJX7h/'
        groups: wheel
        append: yes

    - name: add public matrix account public key
      ansible.posix.authorized_key:
        user: hzhao99
        state: present
        key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCkBM8c5IrRViSwJm01k2+Bgi8nUKU6liIgg/uvIaheC7GqLnqgnegKfJcPp1ZCa+hYWjV/4uhbGENFo3m0u+/eVJjFbYgP9BA4HA9Da1v7BYHCC5QvAj6xV3g+GXacYzhX9YzTbqAkGCb7wYCF2EoxwdsyaQlvqIsugxH4JhW0FxaOe5f/ScWhoLnJ7VXAqgEJpFVcrt7XoCzNSOVGE1haqfzFhif+qZh6PWA58ZmJEfHtIE3uq2pjEFsmGg5Vg65XZYSuAEaEhjNKENaOGNPt89GMmkfIlIKztt4dNaCe5oD7bILGSphAGA/lrHy1iOBwtvaZHWW1Qz4O+123RtWL hzhao99@mtrx-node04pd.dcm.senecacollege.ca'

    - name: create directory structure
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /home/hzhao99/ops445/lab1
        - /home/hzhao99/ops445/lab2
        - /home/hzhao99/ops445/lab3
        - /home/hzhao99/ops445/lab4
        - /home/hzhao99/ops445/lab5
        - /home/hzhao99/ops445/lab6
        - /home/hzhao99/ops445/lab7
        - /home/hzhao99/ops445/lab8
